/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "张嘉家的个人博客",
  "description": "使用VuePress制作的个人博客",
  "base": "/vuePress/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/vuePress/assets/img/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "张嘉家"
      }
    ],
    [
      "meta",
      {
        "name": "keyword",
        "content": "VuePress介绍,VuePress说明,张嘉家个人博客"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "\\assets\\img\\hero.png",
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-1b6c7da9",
      "path": "/",
      "lastUpdated": "Monday, March 1, 2021 4:42 PM"
    },
    {
      "title": "关于我",
      "frontmatter": {
        "title": "关于我"
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-d810321c",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "标题一",
          "slug": "标题一"
        },
        {
          "level": 3,
          "title": "标题1",
          "slug": "标题1"
        },
        {
          "level": 3,
          "title": "标题2",
          "slug": "标题2"
        },
        {
          "level": 3,
          "title": "标题3",
          "slug": "标题3"
        },
        {
          "level": 2,
          "title": "标题二",
          "slug": "标题二"
        },
        {
          "level": 3,
          "title": "标题1",
          "slug": "标题1-2"
        },
        {
          "level": 3,
          "title": "标题2",
          "slug": "标题2-2"
        },
        {
          "level": 3,
          "title": "标题3",
          "slug": "标题3-2"
        }
      ],
      "lastUpdated": "Monday, March 1, 2021 4:42 PM"
    },
    {
      "title": "关于我1",
      "frontmatter": {
        "title": "关于我1"
      },
      "regularPath": "/about1.html",
      "relativePath": "about1.md",
      "key": "v-55226714",
      "path": "/about1.html",
      "headers": [
        {
          "level": 2,
          "title": "标题一",
          "slug": "标题一"
        },
        {
          "level": 3,
          "title": "标题1",
          "slug": "标题1"
        },
        {
          "level": 3,
          "title": "标题2",
          "slug": "标题2"
        },
        {
          "level": 3,
          "title": "标题3",
          "slug": "标题3"
        },
        {
          "level": 2,
          "title": "标题二",
          "slug": "标题二"
        },
        {
          "level": 3,
          "title": "标题1",
          "slug": "标题1-2"
        },
        {
          "level": 3,
          "title": "标题2",
          "slug": "标题2-2"
        },
        {
          "level": 3,
          "title": "标题3",
          "slug": "标题3-2"
        },
        {
          "level": 2,
          "title": "标题三",
          "slug": "标题三"
        },
        {
          "level": 3,
          "title": "标题1",
          "slug": "标题1-3"
        },
        {
          "level": 3,
          "title": "标题2",
          "slug": "标题2-3"
        },
        {
          "level": 2,
          "title": "标题四",
          "slug": "标题四"
        },
        {
          "level": 3,
          "title": "标题1",
          "slug": "标题1-4"
        }
      ],
      "lastUpdated": "Monday, March 1, 2021 3:58 PM"
    },
    {
      "title": "about3",
      "frontmatter": {
        "title": "about3"
      },
      "regularPath": "/about3.html",
      "relativePath": "about3.md",
      "key": "v-c8078d1c",
      "path": "/about3.html",
      "headers": [
        {
          "level": 2,
          "title": "标题一",
          "slug": "标题一"
        },
        {
          "level": 3,
          "title": "标题1",
          "slug": "标题1"
        },
        {
          "level": 3,
          "title": "标题2",
          "slug": "标题2"
        },
        {
          "level": 3,
          "title": "标题3",
          "slug": "标题3"
        },
        {
          "level": 2,
          "title": "标题二",
          "slug": "标题二"
        },
        {
          "level": 3,
          "title": "标题1",
          "slug": "标题1-2"
        },
        {
          "level": 3,
          "title": "标题2",
          "slug": "标题2-2"
        },
        {
          "level": 3,
          "title": "标题3",
          "slug": "标题3-2"
        }
      ],
      "lastUpdated": "Monday, March 1, 2021 4:42 PM"
    },
    {
      "title": "c-aaa",
      "frontmatter": {
        "title": "c-aaa"
      },
      "regularPath": "/css/c-aaa.html",
      "relativePath": "css/c-aaa.md",
      "key": "v-511824e5",
      "path": "/css/c-aaa.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        }
      ],
      "lastUpdated": "Monday, March 1, 2021 4:42 PM"
    },
    {
      "title": "测试",
      "frontmatter": {
        "title": "测试"
      },
      "regularPath": "/about4.html",
      "relativePath": "about4.md",
      "key": "v-7f42eff0",
      "path": "/about4.html",
      "headers": [
        {
          "level": 2,
          "title": "标题一",
          "slug": "标题一"
        },
        {
          "level": 3,
          "title": "标题1",
          "slug": "标题1"
        },
        {
          "level": 3,
          "title": "标题2",
          "slug": "标题2"
        },
        {
          "level": 3,
          "title": "标题3",
          "slug": "标题3"
        },
        {
          "level": 2,
          "title": "标题二",
          "slug": "标题二"
        },
        {
          "level": 3,
          "title": "标题1",
          "slug": "标题1-2"
        },
        {
          "level": 3,
          "title": "标题2",
          "slug": "标题2-2"
        },
        {
          "level": 3,
          "title": "标题3",
          "slug": "标题3-2"
        }
      ],
      "lastUpdated": "Monday, March 1, 2021 4:42 PM"
    },
    {
      "title": "CSS a",
      "frontmatter": {
        "title": "CSS a"
      },
      "regularPath": "/css/",
      "relativePath": "css/README.md",
      "key": "v-0e24e62e",
      "path": "/css/",
      "headers": [
        {
          "level": 2,
          "title": "你好 CSS",
          "slug": "你好-css"
        }
      ],
      "lastUpdated": "Monday, March 1, 2021 4:42 PM"
    },
    {
      "title": "c-bbb",
      "frontmatter": {
        "title": "c-bbb"
      },
      "regularPath": "/css/c-bbb.html",
      "relativePath": "css/c-bbb.md",
      "key": "v-9d0cd976",
      "path": "/css/c-bbb.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        }
      ],
      "lastUpdated": "Monday, March 1, 2021 4:42 PM"
    },
    {
      "title": "c-ccc",
      "frontmatter": {
        "title": "c-ccc"
      },
      "regularPath": "/css/c-ccc.html",
      "relativePath": "css/c-ccc.md",
      "key": "v-11db01a5",
      "path": "/css/c-ccc.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        }
      ],
      "lastUpdated": "Monday, March 1, 2021 4:42 PM"
    },
    {
      "title": "JavaScript",
      "frontmatter": {
        "title": "JavaScript"
      },
      "regularPath": "/javascript/",
      "relativePath": "javascript/README.md",
      "key": "v-4ea176a8",
      "path": "/javascript/",
      "headers": [
        {
          "level": 2,
          "title": "你好 JavaScript",
          "slug": "你好-javascript"
        }
      ],
      "lastUpdated": "Monday, March 1, 2021 4:42 PM"
    },
    {
      "title": "j-bbb",
      "frontmatter": {
        "title": "j-bbb"
      },
      "regularPath": "/javascript/j-bbb.html",
      "relativePath": "javascript/j-bbb.md",
      "key": "v-44d3181e",
      "path": "/javascript/j-bbb.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        }
      ],
      "lastUpdated": "Monday, March 1, 2021 4:42 PM"
    },
    {
      "title": "j-aaa",
      "frontmatter": {
        "title": "j-aaa"
      },
      "regularPath": "/javascript/j-aaa.html",
      "relativePath": "javascript/j-aaa.md",
      "key": "v-131ec7f3",
      "path": "/javascript/j-aaa.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        }
      ],
      "lastUpdated": "Monday, March 1, 2021 4:42 PM"
    },
    {
      "title": "这是测试页面1",
      "frontmatter": {},
      "regularPath": "/test1.html",
      "relativePath": "test1.md",
      "key": "v-4ef3da9c",
      "path": "/test1.html",
      "headers": [
        {
          "level": 2,
          "title": "这是测试页面1",
          "slug": "这是测试页面1"
        }
      ],
      "lastUpdated": "Monday, March 1, 2021 4:42 PM"
    },
    {
      "title": "这是测试页面2",
      "frontmatter": {},
      "regularPath": "/test2.html",
      "relativePath": "test2.md",
      "key": "v-34165592",
      "path": "/test2.html",
      "headers": [
        {
          "level": 2,
          "title": "这是测试页面2",
          "slug": "这是测试页面2"
        }
      ],
      "lastUpdated": "Monday, March 1, 2021 4:42 PM"
    },
    {
      "title": "j-ccc",
      "frontmatter": {
        "title": "j-ccc"
      },
      "regularPath": "/javascript/j-ccc.html",
      "relativePath": "javascript/j-ccc.md",
      "key": "v-afe3c022",
      "path": "/javascript/j-ccc.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        }
      ],
      "lastUpdated": "Monday, March 1, 2021 4:42 PM"
    }
  ],
  "themeConfig": {
    "lastUpdated": "更新时间",
    "logo": "/assets/img/hero.png",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "About",
        "link": "/about"
      },
      {
        "text": "About1",
        "link": "/about1"
      },
      {
        "text": "CSS",
        "link": "/css/"
      },
      {
        "text": "JavaScript",
        "link": "/javascript/"
      },
      {
        "text": "Languages",
        "items": [
          {
            "text": "Group1",
            "items": [
              {
                "text": "test1",
                "link": "/test1"
              },
              {
                "text": "test2",
                "link": "/test2"
              }
            ]
          },
          {
            "text": "Group2",
            "items": [
              {
                "text": "test1",
                "link": "/test1"
              },
              {
                "text": "test2",
                "link": "/test2"
              }
            ]
          }
        ]
      },
      {
        "text": "External",
        "link": "https://google.com"
      }
    ],
    "sidebar": {
      "/css/": [
        "",
        "c-aaa",
        "c-bbb",
        "c-ccc"
      ],
      "/javascript/": [
        "",
        "j-aaa",
        "j-bbb",
        "j-ccc"
      ],
      "/": [
        "",
        "about",
        "about1"
      ]
    }
  }
}